# VARIABLES
# ---------
title: Halo 3 Archives
copyright: "Copyright 2009 Webspirited. All Rights Reserved."


# JEKYLL
# ------
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor
    - Makefile
    - Dockerfile
